# Generated by Django 4.2.4 on 2023-12-28 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_name', models.CharField(max_length=100)),
                ('news_link', models.CharField(max_length=2000)),
                ('news_date', models.DateTimeField(auto_now=True)),
                ('news_text', models.TextField()),
                ('news_source', models.CharField(max_length=20)),
                ('news_category', models.CharField(default='General', max_length=20)),
                ('news_image', models.ImageField(blank=True, null=True, upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=15)),
                ('user_surname', models.CharField(max_length=20)),
                ('user_email', models.EmailField(max_length=30)),
                ('user_comment', models.TextField()),
                ('comment_date', models.DateTimeField(auto_now=True)),
                ('comment_number', models.IntegerField()),
                ('news_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.news')),
            ],
        ),
    ]
